ARG VERSION

## base, for dealing with coping files etc...
FROM node:lts AS base
WORKDIR /usr/src/app

EXPOSE 8080

COPY . ./
RUN npm i
## dev version, with nodemon and volumes for easy development
FROM base as runner
CMD ["npm", "start"]